-- High-frequency jobs must not consume GitHub Actions runners. Keep the
-- environment-specific URL and cron secret in Vault; migrations only own the
-- private dispatch boundary and its audit ledger.
create extension if not exists pg_cron;
create extension if not exists pg_net with schema extensions;
create extension if not exists supabase_vault with schema vault;

create schema if not exists kv_ops;
revoke all on schema kv_ops from public, anon, authenticated;

create table kv_ops.schedule_dispatches (
  id bigint generated by default as identity primary key,
  job_name text not null,
  endpoint text not null,
  request_id bigint not null,
  enqueued_at timestamptz not null default now()
);

create index schedule_dispatches_job_time_idx
  on kv_ops.schedule_dispatches (job_name, enqueued_at desc);

alter table kv_ops.schedule_dispatches enable row level security;
revoke all on table kv_ops.schedule_dispatches from public, anon, authenticated;

create or replace function kv_ops.dispatch_scheduled_endpoint(
  p_job_name text,
  p_endpoint text
) returns bigint
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_base_url text;
  v_cron_secret text;
  v_request_id bigint;
begin
  if p_endpoint <> all (array[
    '/api/cron/visit-timeout',
    '/api/cron/support-daily-report',
    '/api/cron/team-lead-report',
    '/api/cron/metric-snapshot',
    '/api/cron/kb-recheck'
  ]) then
    raise exception 'Unsupported KV scheduled endpoint: %', p_endpoint;
  end if;

  select decrypted_secret into v_base_url
  from vault.decrypted_secrets
  where name = 'kv_app_base_url';

  select decrypted_secret into v_cron_secret
  from vault.decrypted_secrets
  where name = 'kv_cron_secret';

  if nullif(btrim(v_base_url), '') is null or nullif(btrim(v_cron_secret), '') is null then
    raise exception 'KV schedule Vault secrets are not configured';
  end if;

  select net.http_get(
    url := rtrim(v_base_url, '/') || p_endpoint,
    headers := jsonb_build_object('x-cron-key', v_cron_secret),
    timeout_milliseconds := case when p_endpoint = '/api/cron/kb-recheck' then 300000 else 120000 end
  ) into v_request_id;

  insert into kv_ops.schedule_dispatches (job_name, endpoint, request_id)
  values (p_job_name, p_endpoint, v_request_id);

  return v_request_id;
end;
$$;

revoke all on function kv_ops.dispatch_scheduled_endpoint(text, text) from public, anon, authenticated;
grant usage on schema kv_ops to postgres;
grant execute on function kv_ops.dispatch_scheduled_endpoint(text, text) to postgres;

create or replace function kv_ops.prune_schedule_dispatches()
returns bigint
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_deleted bigint;
begin
  delete from kv_ops.schedule_dispatches
  where enqueued_at < now() - interval '7 days';
  get diagnostics v_deleted = row_count;
  return v_deleted;
end;
$$;

revoke all on function kv_ops.prune_schedule_dispatches() from public, anon, authenticated;
grant execute on function kv_ops.prune_schedule_dispatches() to postgres;
